### ISSUE TITLE
module manifest don't have ExportedFunctions property

### ISSUE THREAD

**Issue by peetrike** [EvotecIT/GPOZaurr#1]
the result is, that `Get-Command` doesn-t show module commands until after importing module.  And module autoload doesn't work.

**Comment by peetrike** [comment]
The problem was caused by missing directory in `$env:PSModulePath`.  So, case closed

**Comment by PrzemyslawKlys** [comment]
Good. PSD1 is autogenerated and it must have that - or at least should :-)
