### ISSUE TITLE
GPOAnalysis doesn't appear to capture all GPOs with Folder Redirects

### ISSUE THREAD

**Issue by pkutzner** [EvotecIT/GPOZaurr#11]
I recently ran a GPOAnalysis against our domain, and the Folder Redirect tab only pulled 2 of our GPOs that have folder redirects configured.  We have more GPOs than this that do have this setting, of which I'm trying to get a proper count.  But a quick spot-check showed that at least one that is present in the forest that wasn't captured in the report.

**Comment by PrzemyslawKlys** [comment]
Would you be able to provide export in form of XML for GPO that was not included in that report? 

Are folder redirects built the same way for all GPOs? or is it possible they differ slightly?

**Comment by pkutzner** [comment]
They're all the same, Basic folder redirection of Documents, with the sub-folders set to 'Follow the Documents folder'

**Comment by PrzemyslawKlys** [comment]
can you give me the full path to where it's set? 

Is it?
- User Configuration -> Windows Settings -> Folder Redirection?

**Comment by pkutzner** [comment]
Yup  User Config -> Policies -> Windows Settings -> Folder Redirection:
Right-click on Documents, Setting: Basic - Redirect everyone's folders to the same location
Target folder location: Create a folder for each user under the root path
Root Path: \\server.fq.dn\share$

**Comment by PrzemyslawKlys** [comment]
i'll try to reproduce it and if there's something missing fix it. From what I see FolderRedirection currently added supports different folder redirection... and that's why you see a difference. 

```powershell
    FolderRedirection                 = @{
        Types      = @(
            @{
                Category = 'RegistrySettings'
                Settings = 'Policy'
            }
        )
        GPOPath    = 'Policies -> Administrative Templates -> System/Folder Redirection'
        Code       = {
            ConvertTo-XMLGenericPolicy -GPO $GPO -Category 'System/Folder Redirection'
        }
        CodeSingle = {
            ConvertTo-XMLGenericPolicy -GPO $GPO -Category 'System/Folder Redirection' -SingleObject
        }
    }
```

**Comment by pkutzner** [comment]
Okay, so it looks like the two that *were* captured have User Config -> Administrative Templates -> System/Folder Redirection -> Do not automatically make all redirected folders available offline set to Enabled  I'm checking others.  The one I know didn't get captured does *not* have this setting.

**Comment by pkutzner** [comment]
Yes, so, is it possible to have a report that shows GPOs with Policies -> Windows Settings -> Folder Redirection set, versus Administrative Templates -> System/Folder Redirection?  Or, is that found in another tab?

**Comment by pkutzner** [comment]
I ask this, as it can be useful.  In our case, we're auditing our GPOs for folder redirections to a) servers that no longer exist, and b) servers using only NETBIOS names instead of FQDNs.

**Comment by pkutzner** [comment]
As an aside,  I also noticed that this report provides the GPO links as CanonicalName, versus the DistinguishedName of other reports.  Not sure if that is intentional or not.

**Comment by PrzemyslawKlys** [comment]
GPO Links by default should be treated in this report informational only. The problem is links are extracted from XML. The XML however doesn't have links from sites or cross-domain links which makes them useless and false negative information potentially providing wrong data.

That's why GPOList or other LInk based reports are building it using different way. 

The Feature Request makes sense and I'll consider adding it. Anything based on RegistrySettings/Policy as seen above for current FolderRedirectioon is basically copy and paste for multiple reports. I need to see what is required to read and provide output for Folders. Maybe I can do it without much effort from my side.
