### ISSUE TITLE
Feature Request: Add Windows Settings -> Folder Redirection details report.

### ISSUE THREAD

**Issue by pkutzner** [EvotecIT/GPOZaurr#12]
Request to either add Windows Settings -> Folder Redirection details (including source and target) to the Folder Redirection tab in the GPOAudit report, or either have a separate tab or separate report for this. 

It would be beneficial to have a quick look at all folder redirection targets to spot problems (e.g. invalid servers or paths, servers referenced only via NETBIOS vs FQDN, etc.)

Currently a list of GPOs that have this setting set can be generated from the GPOReport report by filtering on the 'UserPolicies' column for 'Folder Redirection'.  However, from there, one has to touch each GPO to find out the redirection target information.  This can be tedious if there are many GPOs with folder redirection settings enabled.

**Comment by PrzemyslawKlys** [comment]
Added to both `Invoke-GPOZaurr -Type GPOAnalysis` and `Invoke-GPOZaurrContent` (which is the console version of GPOAnalysis).
