### ISSUE TITLE
Feature Request: Include GPO Description field to GPOList output.

### ISSUE THREAD

**Issue by pkutzner** [EvotecIT/GPOZaurr#13]
I noticed this exists in the GPOConsistency report output, but I think it would make sense to also have it in the GPOList output as well.

**Comment by PrzemyslawKlys** [comment]
![image](https://user-images.githubusercontent.com/15063294/107554095-c27b5200-6bd5-11eb-83a4-131310baefee.png)

added, it's not easily visible but it's there. Planned for 0.0.121
