### ISSUE TITLE
Issues detecting group policy links; blank reports

### ISSUE THREAD

**Issue by wrinks76** [EvotecIT/GPOZaurr#15]
Hello,

When I user Invoke-GPOzaurr, there are portions of the report that come up blank: Group Policy Links, Group Policy Root Permissions, Group Policy Content, and Group Policy Passwords. Additionally, when I look at the Group Policy Summary report, it says the vast majority of my policies are unlinked, even though they are linked. The other reports appear to run correctly

With the Group policy Owner portion, I get this Warning for each GPO:
`WARNING: Set-ADACLOwner - Drive CN{31B2F340-016D-11D2-945F-00C04FB984F9}CNPoliciesCNSystemDCSARASOTA not mapped.
Terminating...`

Group policy summary yields:
`WARNING: Get-PrivGPOZaurrLink - Couldn't find link
cn={84187EC3-FB32-458E-9800-0A577F6AADEF},cn=policies,cn=system.SARASOTA84187EC3-FB32-458E-9800-0A577F6AADEF in a GPO Cache. Lack of permissions for given GPO? Are you running as admin? Skipping.`
Group Policy links yields the same warning as GPO Summary
Get-GPOReport Yeilds:
```Get-GPOReport : The format of the specified domain name is invalid. (Exception from HRESULT: 0x800704BC)
At C:\Program Files\WindowsPowerShell\Modules\GPOZaurr\0.0.126\GPOZaurr.psm1:17964 char:32
+ ... GPOOutput = Get-GPOReport -Guid $GPO.GUID -Domain $GPO.DomainName -Re ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Get-GPOReport], COMException
    + FullyQualifiedErrorId : System.Runtime.InteropServices.COMException,Microsoft.GroupPolicy.Commands.GetGpoReportC
   Ommand```
I am running as a domain admin, and that group appears to have the correct permissions for these GPOs. Am I missing something?

**Comment by PrzemyslawKlys** [comment]
Domain Admin is not nessecary for the reports to work. 

1. Do you have English based domain?
2. What forest version?
3. What domain version?
4. What Windows Server? 
5. What workstation you're running it from? 
6. Do you have newest AD/GPO module from RSAT?

**Comment by wrinks76** [comment]
1. Yes
2. Windows Server 2008 R2
3. Windows Server 2008 R2
4. Server it's pulling the report from should be a Win Server 2019 
5. Running from a Win10 workstation on my domain. I've also ran in directly on the Win2019 DC with the same results
6. I believe I do. I installed RSAT in late Feb, though I'm not sure how to check the version.

**Comment by PrzemyslawKlys** [comment]
I have never tested on 2008R2. May be a reason.

**Comment by PrzemyslawKlys** [comment]
Keep in mind that it's possible the GPOZaurr auto-targets other servers,m not the one you're currently using.

**Comment by wrinks76** [comment]
Gotcha, is there a way to make it target the Win2019 server?

**Comment by PrzemyslawKlys** [comment]
```powershell
Get-ADDomainController -Discover -Writable
```

See what you get - if you get here Windows 2008R2 then most likely that's the problem. I don't think I added any force of server to use.

**Comment by wrinks76** [comment]
It's pointing to the Windows 2019 server.

**Comment by PrzemyslawKlys** [comment]
Then I have no ideas - probably somehow Windows 2008 R2 gets mixed. Without debugging code right on your domain it would be hard. You could try separate cmdlets like Get-GPOZaurr and all other Get-* commands and see the ones which works, which don't and go from there.

**Comment by wrinks76** [comment]
Gotcha. I'll see if I can get anymore info. I appreciate the response!

**Comment by jdmtechbr** [comment]
Hi @PrzemyslawKlys 
I am getting some warnings like "Get-PrivGPOZaurrLink - Couldn't find link DomainGUID in a GPO Cache. Lack of permissions for given GPO? Are you running as admin? Skipping"

When I run a "Get-GPO -guid xxxx" with the GUID that was presented in the warning, cmdLet Get-GPO does not find that Guid. Could you tell me why this behavior?

**Comment by PrzemyslawKlys** [comment]
Run BrokenLinks report. If you are running the tool as Domain Admin/Enterprise Admin, most likely someone deleted a GPO and left links still linked.
