### ISSUE TITLE
Remove-GPOZaurrBroken -Type AD

### ISSUE THREAD

**Issue by kuroboshi** [EvotecIT/GPOZaurr#16]
Hello,
When i launch this command : Remove-GPOZaurrBroken -Type AD -LimitProcessing 2 -Verbose
I have this warm :
AVERTISSEMENT : Remove-GPOZaurrBroken - DistinguishedName CN={AE7CC155-CA5C-4963-B920-4565F4802F22},CN=Policies,CN=System,DC=domain,DC=local not found or ObjectClass is not groupPolicyContainer/C
ontainer ()

The GPO "Not available on SYSVOL" is still here

    Do you have English based domain? No its French
    What forest version? 2016
    What domain version? 2016
    What Windows Server? 2019
    What workstation you're running it from? directly on DC

**Comment by PrzemyslawKlys** [comment]
GO into your AD and check type in this folder. Can you see that ID? What type it has?

![image](https://user-images.githubusercontent.com/15063294/116983740-c39ab780-acca-11eb-9d87-ad982a6b07d7.png)

**Comment by kuroboshi** [comment]
here is
![image](https://user-images.githubusercontent.com/22149432/116984025-13797e80-accb-11eb-9b38-4e70bfd58c48.png)

**Comment by kuroboshi** [comment]
Can i delete directly on this screen without trouble ?

**Comment by PrzemyslawKlys** [comment]
Do you have the corresponding folder on sysvol?

**Comment by kuroboshi** [comment]
No

**Comment by PrzemyslawKlys** [comment]
I don't know french but does it say lack of permission or Inconnu means container? 

what does `Remove-GPOZaurrBroken -Type ObjectClass -WhatIf -Verbose` says? does it see that folder?

**Comment by kuroboshi** [comment]
He see the GPO :
COMMENTAIRES : Get-GPOZaurrBroken - Processing [domain.local](32/48) {AE7CC155-CA5C-4963-B920-4565F4802F22}
COMMENTAIRES : Get-GPOZaurrBroken - Processing SYSVOL differences

**Comment by PrzemyslawKlys** [comment]
if you don't have sysvol content - you either give back permission to DOmain Admin and let the script delete it or you remove it - but make sure there is no sysvol content

**Comment by kuroboshi** [comment]
It's okay, I deleted it. I applied the rights like the other objects and this fixed the problem

thank you for your help
