### ISSUE TITLE
Question - Organizational Unit

### ISSUE THREAD

**Issue by brink668** [EvotecIT/GPOZaurr#32]
Would you be able to provide some examples on/if we can target an Organization Unit with Invoke-GPOZAurr?

I could not find the right syntax and the Organization Unit DOC does not seem complete.

**Comment by PrzemyslawKlys** [comment]
You won't be able to because it would give you incorrect data. Even querying just the domain can give you incorrect data. Maybe some reports would work, but most of them would just not report properly. 

What report are you interested in?

**Comment by brink668** [comment]
I am interested in trying to find duplicate settings/conflicting settings across Group Policies.  My current process has been manual, while it has worked it is extremely laborious work.

Currently GPOAnalysis is running against the domain but currently been pending on "Generating HTML" for the last 30 mins.  

I still have to see if something may be blocking it.

**Comment by PrzemyslawKlys** [comment]
you can enable -vErbose and it will show you gpo by gpo what it's doing - it may take time as it's basically requesting all XMLs and parsing them.

**Comment by brink668** [comment]
Thank you I will try with the Verbose command
