### ISSUE TITLE
Get-LocalComputerSid - Error: You cannot call a method on a null-valued expression

### ISSUE THREAD

**Issue by LemurTech** [EvotecIT/GPOZaurr#34]
In 0.0.154, during tests that analyze permissions, and while running on a Domain Controllers, I see the warning message "Get-LocalComputerSid - Error: You cannot call a method on a null-valued expression." It appears repeatedly, perhaps for every GPO being analyzed.

Is this something to address, or truly just informational? I only see one minor permissions issue among my GPOs.

**Comment by PrzemyslawKlys** [comment]
Well this is done during conversion of SIDs. 

```powershell
function Get-LocalComputerSid {
    [cmdletBinding()]
    param()
    try {
        $LocalAccountSID = Get-CimInstance -Query "SELECT SID FROM Win32_UserAccount WHERE LocalAccount = 'True'" -ErrorAction Stop | Select-Object -First 1 -ExpandProperty SID
        $LocalAccountSID.TrimEnd("-500")
    } catch {
        Write-Warning -Message "Get-LocalComputerSid - Error: $($_.Exception.Message)"
    }
}
Get-LocalComputerSid
```

Does that work when you run it manually?

**Comment by SysadminRyan** [comment]
Just to confirm im having the same issue and the above function returns the same error and not the SID

**Comment by PrzemyslawKlys** [comment]
What you get if you just paste it like that?

![image](https://user-images.githubusercontent.com/15063294/200313060-7bef97b7-7bd3-4c91-b6de-f679f235c518.png)

**Comment by PrzemyslawKlys** [comment]
I'll replace the function alltogether:

```powershell
Add-Type -AssemblyName System.DirectoryServices.AccountManagement
$PrincipalContext = New-Object System.DirectoryServices.AccountManagement.PrincipalContext([System.DirectoryServices.AccountManagement.ContextType]::Machine)
$UserPrincipal = New-Object System.DirectoryServices.AccountManagement.UserPrincipal($PrincipalContext)
$Searcher = New-Object System.DirectoryServices.AccountManagement.PrincipalSearcher
$Searcher.QueryFilter = $UserPrincipal
$User = $Searcher.FindAll() | Where-Object { $_.Sid -Like "*-500" }
$User.Sid.Value.TrimEnd("-500")
```

Can you try it?

**Comment by SysadminRyan** [comment]
That seems to have cleared the null-valued errors, appreciate your efforts!

**Comment by PrzemyslawKlys** [comment]
I need to fix few other things and I will release fixed version with this fix.

**Comment by krzydoug** [comment]
I came to say I encountered this same issue. I was going to do a pull request but I see you're new solution worked on the DC I was getting the error on. It returned a SID where the original does not. Thank you for everything you do, you are very much appreciated.
