### ISSUE TITLE
Running just invoke-gpozaurr is splitting reports every time. 

### ISSUE THREAD

**Issue by wiegz15** [EvotecIT/GPOZaurr#35]
The command used to not split the reports when run alone.  Do I need to add a new parameter to the command to get the full report in one html?

**Comment by PrzemyslawKlys** [comment]
This was fixed in last release. Did you update?

**Comment by PrzemyslawKlys** [comment]
Are you running it like that?

```powershell
 Invoke-GPOZaurr -Type GPOOwners,GPOConsistency -Online
``` 

or without any parameters?

**Comment by PrzemyslawKlys** [comment]
Ok, i see, no parameters - still splits.

**Comment by PrzemyslawKlys** [comment]
It's fixed, new version released.

**Comment by wiegz15** [comment]
Thanks!
