### ISSUE TITLE
Filename processing issue

### ISSUE THREAD

**Issue by LemurTech** [EvotecIT/GPOZaurr#37]
In version 0.0.156, you have a bit of code in GPOZaurr.psm1 at line 15301 which is meant to add the date ($DateName) to the filename for split reports. The problem seems to be that single reports are still being processed as "split" reports, and when you feed "invoke-GPOZaurr" a filename the resulting save path gets formatted in an unexpected way.

In the example output below, the filename "GPODuplicates_2022-12-07.html" is transformed into "GPODuplicates_2022-12-07_GPODuplicates_2022-12-07_140933.html":

...
[i][Start] Duplicate (CNF) Group Policies
[i][End  ] Duplicate (CNF) Group Policies [Time to execute: 0 days, 0 hours, 0 minutes, 0 seconds, 594 milliseconds]
[i][HTML ] Generating HTML report (C:\inetpub\wwwroot\Domain Health\GPO Audits\2022-12-07\GPODuplicates_2022-12-07_GPODuplicates_2022-12-07_140933.html) for GPODuplicates with split reports

**Comment by PrzemyslawKlys** [comment]
Care for a PR?

**Comment by LemurTech** [comment]
I would, but I don't really understand how you would want to fix the issue. I just ended up recoding that line to remove the name change, since I don't need the split reports functionality just now.

**Comment by LemurTech** [comment]
Looks like it works now. Thanks, Prem!
