### ISSUE TITLE
Group Policy Content - GPO Subfolders

### ISSUE THREAD

**Issue by Mrake5** [EvotecIT/GPOZaurr#38]
Wanted to request the ability for the 'Group Policy Content' report to show all subfolders specifically for Google Chrome ADMX templates.

Currently, GPOZaurr only shows the top-level settings: (i.e. Policies -> Administrative Templates -> Google -> Google Chrome)

It doesn't show any of the settings nested in any of the following subfolders however:

![image](https://user-images.githubusercontent.com/35434035/207396275-4fda6853-cbd3-4565-8a6e-6c40070e6965.png)

**Comment by PrzemyslawKlys** [comment]
The change you are requesting is pretty trivial:

https://github.com/EvotecIT/GPOZaurr/blob/ea7b4f1bd83e5fb4604fd859a54936fc44d7afc7/Private/Script.GPODictionary.ps1#L396-L399

Should more or less look like this:

https://github.com/EvotecIT/GPOZaurr/blob/ea7b4f1bd83e5fb4604fd859a54936fc44d7afc7/Private/Script.GPODictionary.ps1#L411-L414

So what's missing is wildcard to the right of category. You can test it out and maybe create a PR?
