### ISSUE TITLE
Empty OU detection doesn't acknowledge AD printers

### ISSUE THREAD

**Issue by SirMikeDouglas** [EvotecIT/GPOZaurr#39]
The OU scan appears to only see Users, Computers and Groups when giving the recommendation to delete an "empty" OU. Manually going through the list I noticed a couple of our recommended OUs to delete were well populated with printer objects.

**Comment by PrzemyslawKlys** [comment]
It's doing a bit more. 

```powershell
Get-ADObject -LDAPFilter "(|(ObjectClass=user)(ObjectClass=contact)(ObjectClass=computer)(ObjectClass=group)(objectClass=inetOrgPerson))"
```

Would you be able to test proper ADObject filter as I don't have printers in my domain.

**Comment by SirMikeDouglas** [comment]
I can definitely test. What all do you need me to do? Just add a (ObjectClass=printer) in that?

**Comment by PrzemyslawKlys** [comment]
Ye, pretty much - if that is the printer object that you see. If it returns them including others - we should be good.

**Comment by SirMikeDouglas** [comment]
OK, will do. I forwarded the email to my work and will test on Monday.

**Comment by SirMikeDouglas** [comment]
Looks like it has to be PrintQueue not Printer.

 

(ObjectClass=PrintQueue)

**Comment by Karl-WE** [comment]
Having no printers is a good idea for less headache. But seriously you can install use any Windows Server share a printer and right click publish them to AD. Not sure if a printing role is needed (eventually it is)

**Comment by SirMikeDouglas** [comment]
I agree but I inherited this and I have to work with what I have. By the way, kudos on a job extremely well done. I’m loving GPOZaurr as it has found lots of things from previous admins that have done so many things I never would have.  This has gone from a simple audit to a daily project and many Change Requests for corrective actions. Thank You

**Comment by Karl-WE** [comment]
I believe when publishing printers to AD they are all located in one specific OU.

Can one elaborate why it should be feasible to move these Auto generated print queue objects around to other User OUs?

@PrzemyslawKlys have my comment been helpful for you how to create AD printer objects?

**Comment by PrzemyslawKlys** [comment]
I don't think it's about moving (while you may need that for an answer), but a script marked OU as empty when objects were inside. This is wrong and should be now fixed. 

As for creating Printer objects, I don't think I need them in my AD ;)
