### ISSUE TITLE
Extra spaces in property name 'Id'  in Get-GPOZaurrPermissionConsistency?

### ISSUE THREAD

**Issue by ssg47** [EvotecIT/GPOZaurr#44]
I ran this:

    $GPOInconsistentPerms = Get-GPOZaurrPermissionConsistency -IncludeDomains (Get-ADDomain).DNSRoot

and then this:

    $GPOInconsistentPerms.Where({ $_.id -eq '15b4308d-9faf-425a-ba63-a786b916f242'})

and got no output, which was odd as I'd copied the GUID from the `Invoke-GPOZaurr` report I'd also just run.  After too much fiddling and not enough thinking, I tab-completed it and got this:

    $GPOInconsistentPerms[101].'Id       '

Looking in the file for `Get-GPOZaurrPermissionConsistency` on line 99, you have this:

    $Object['Id       '] = $_.Id              # : 8a7bc515-d7fd-4d1f-90b8-e47c15f89295

Is it supposed to be like that?

**Comment by PrzemyslawKlys** [comment]
Nah, it's a bug if it's like that :)
