### ISSUE TITLE
GPOConsistency - Missing Method

### ISSUE THREAD

**Issue by scalfbenjamin** [EvotecIT/GPOZaurr#45]
When running both the full report and the specific "Invoke-GPOZaurr -Type GPOConsistency" commands, the return errors out w/ the following error:

[i][Start] GPO Permissions Consistency
VERBOSE: Get-GPOZaurrPermissionConsistency - Starting process for domainname.local
VERBOSE: Get-GPOZaurrPermissionConsistency - Processing [domainname.local](1/7) WinAll-SChannel
WARNING: Get-GPOZaurrPermissionConsistency - Processing GPO-Name / domainname.local failed to get consistency with error: Method invocation failed because [Deserialized.Microsoft.GroupPolicy.Gpo] does not contain a method named 'IsAclConsistent'..

This has been tested and confirmed only in Powershell 7.

This occurs whether the module is imported or imported w/ "-SkipEditionCheck" switch.

If the module is imported w/o "-SkipEditionCheck" I receive the following (possibly unrelated) warnings:
WARNING: Module GroupPolicy is loaded in Windows PowerShell using WinPSCompatSession remoting session; please note that all input and output of commands from this module will be deserialized objects. If you want to load this module into PowerShell please use 'Import-Module -SkipEditionCheck' syntax.
WARNING: Module ActiveDirectory is loaded in Windows PowerShell using WinPSCompatSession remoting session; please note that all input and output of commands from this module will be deserialized objects. If you want to load this module into PowerShell please use 'Import-Module -SkipEditionCheck' syntax.

**Comment by PrzemyslawKlys** [comment]
You can replicate this using:

```powershell
$GPO = Get-GPO -All
$GPO[0].IsAclConsistent()
```

Unfortunetly GroupPolicy was never fully updated to support PowerShell 7, I am not sure why, but I guess most of the functionality just works, but some, do not. Until Microsoft fixes this, we have to use PS 5.1 for GPOZaurr full functionality.
