### ISSUE TITLE
AGPM using GMSA not shown as "Non-Administrative, but approved Owners (for example AGPM):"

### ISSUE THREAD

**Issue by lopeztaz** [EvotecIT/GPOZaurr#46]
The "Group Policy Owners" tab shows AGPM GMSA accounts as "Non-Administrative Owners" in report instead of "Non-Administrative, but approved Owners (for example AGPM)".  Could be due to needing Get-ADServiceAccount instead of Get-ADUser when using service accounts. GMSA account is a member of "Group Policy Creator Owners" group.

**Comment by PrzemyslawKlys** [comment]
So we don't detect whether you use AGPM or not, and we only say Administrative for Domain Admins, Enterprise Admins. As AGPM in whatever form is still valid there's a way to mark it "approved". 

Just provide exclusions `Invoke-Gpozaurr -Exclusions ' "sv\AGPM" -OtherParameters` and it will ignore it

**Comment by lopeztaz** [comment]
It's not really an AGPM issue per say. It's that MSA or GMSA accounts are different objects in AD compared to regular user accounts. So, the GMSA service account object (Not user object) is not detected as being a member of the "Group Policy Creator Owners" group in the script. The account is displayed as "sv\gmsa_account$". It also uses a different command:
(Get-ADServiceAccount "gmsa_account").ObjectGUID | Get-ADPrincipalGroupMembership

I also tried the exclusion and it did not have an effect.
Thank you and I appreciate your work and response.

**Comment by PrzemyslawKlys** [comment]
`Invoke-Gpozaurr -Exclusions "sv\AGPM" -OtherParameters ` -> just add your exclusion in there and it should work. DomainName\SamAccountName
