### ISSUE TITLE
Adding additional GPO dictionary entries

### ISSUE THREAD

**Issue by arielf-mn** [EvotecIT/GPOZaurr#47]
How would I go about adding more entries to this? I'd like to include Office 20xxx as well besides just Outlook. This would be great as folks transition from Office 201x to Office 365.

**Comment by PrzemyslawKlys** [comment]
To modify this all you have to do is change:
- https://github.com/EvotecIT/GPOZaurr/blob/91ff9da014596f15c916ea02786d29f101f97ded/Private/Script.GPODictionary.ps1

If you add more hashtable entries and just follow the pattern - it will work. Code, CodeSingle and Types are the important bit. GPOPath not so much
