### ISSUE TITLE
Is GPOzaurr checking changed/unusual "gPCFileSysPath" AD attribute in an GPO?

### ISSUE THREAD

**Issue by BertMueller18** [EvotecIT/GPOZaurr#48]
I read an article from [Sending GPOs Down the Wrong Track–Redirecting the GPT](https://sdmsoftware.com/security-related/sending-gpos-down-the-wrong-track-redirecting-the-gpt/) about redirected group Policy template paths with. Is it possible to check for that in gpozaurr?

I love the gpozaurr module. Thank you for your hard work and compassion.

**Comment by PrzemyslawKlys** [comment]
I see, so you're essentially looking for a report that shows whether there is a redirect present in GPOs to detect security issues. I'll cook something up

**Comment by PrzemyslawKlys** [comment]
Here's how the new report looks like:

![image](https://github.com/EvotecIT/GPOZaurr/assets/15063294/7a587487-5530-48f1-943a-21515cd725c3)

```powershell
Invoke-GPOZaurr -Online -FilePath $PSScriptRoot\Reports\GPOZaurr.html -Type GPORedirect -PassThru
```
