### ISSUE TITLE
GPOs created using 3rd party extensions recognized as empty even if they are not

### ISSUE THREAD

**Issue by Monarch46a** [EvotecIT/GPOZaurr#49]
Hi! We have the problem that GPOZaurr is reporting GPOs as empty that have been created using a 3rd party MMC extension. In our case, the affected GPOs contain Citrix policies.

**Comment by PrzemyslawKlys** [comment]
Without XML export of those I can't tell you much. Maybe they have different format. Are there any errors reported while scanning for empty?

**Comment by PrzemyslawKlys** [comment]
`Get-GPOReport -ID $GPO.ID -ReportType XML`

**Comment by Monarch46a** [comment]
Here's the XML (redacted):

[gpo.xml.txt](https://github.com/EvotecIT/GPOZaurr/files/12727468/gpo.xml.txt)

**Comment by PrzemyslawKlys** [comment]
Now look at that output and find me any relevant setting from what you see in User Configuration screenshot. All the settings are not there as far as I can tell. Which is very weird, but it's how it looks.

**Comment by PrzemyslawKlys** [comment]
Can you maybe do a backup and provide me backup after redacting? Maybe it's writting it somewhere else, nmaybe it's some sort of legacy setting that's stored in .ini

**Comment by Monarch46a** [comment]
I've made a backup of the GPO, it is attached here. 
[GPO.zip](https://github.com/EvotecIT/GPOZaurr/files/12729498/GPO.zip)

The policy contains Citrix settings from 2021. So not the most current version, but not very old either. In the backup the settings are visible. 

There is no ADMX file because the Citrix software extends the GPO editor from Microsoft. See screenshot below.
![image](https://github.com/EvotecIT/GPOZaurr/assets/146081424/56f19bac-8e20-47a3-b479-3aef12347ad3)

**Comment by Monarch46a** [comment]
Addition - here is an explanation from Citrix: https://support.citrix.com/article/CTX238166/how-to-manage-citrix-gpos-outside-of-the-ddc-using-ms-gpmc

The Citrix Policies only are visible if the CitrixGroupPolicyManagement_x64.msi is installed on the machine via that you are working on the GPO.

**Comment by PrzemyslawKlys** [comment]
I believe new version will work correctly. I am now specifically checking for GPF files and adding FilesCount information for better assesment.

**Comment by PrzemyslawKlys** [comment]
Do let me know if it doesn't fix your issue.
