### ISSUE TITLE
Stuck on Generating HTML report

### ISSUE THREAD

**Issue by SnakeSK** [EvotecIT/GPOZaurr#50]
After updating to the latest version (from .158 I think?), the script is stuck (currently 4 hours) on "Generating HTML report _<filename>_"

In the powershell event log there is this

```
Pipeline execution details for command line:                     $Value = ConvertTo-StringByType -Value $Object[$a].$Property -DateTimeFormat $DateTimeFormat -NumberAsString:$NumberAsString -BoolAsString:$BoolAsString -Depth $InitialDepth -MaxDepth $MaxDepth -TextBuilder $TextBuilder -NewLineFormat $NewLineFormat -NewLineFormatProperty $NewLineFormatProperty -Force:$Force -ArrayJoin:$ArrayJoin -ArrayJoinString $ArrayJoinString -AdvancedReplace $AdvancedReplace


Context Information: 
	DetailSequence=3
	DetailTotal=3

	SequenceNumber=1123175

	UserId=DOMAIN\SERVER_ADMIN
	HostName=ConsoleHost
	HostVersion=5.1.17763.4974
	HostId=335d65a3-d3f1-4f48-bdd1-c8d71b5b42bb
	HostApplication=C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe
	EngineVersion=5.1.17763.4974
	RunspaceId=47d76c5f-ed7c-497c-99ff-81db7d2db4f1
	PipelineId=46
	ScriptName=C:\Program Files\WindowsPowerShell\Modules\PSWriteHTML\1.9.0\PSWriteHTML.psm1
	CommandLine=                    $Value = ConvertTo-StringByType -Value $Object[$a].$Property -DateTimeFormat $DateTimeFormat -NumberAsString:$NumberAsString -BoolAsString:$BoolAsString -Depth $InitialDepth -MaxDepth $MaxDepth -TextBuilder $TextBuilder -NewLineFormat $NewLineFormat -NewLineFormatProperty $NewLineFormatProperty -Force:$Force -ArrayJoin:$ArrayJoin -ArrayJoinString $ArrayJoinString -AdvancedReplace $AdvancedReplace
 

Details: 
ParameterBinding(ConvertTo-StringByType): name="NewLineFormat"; value="System.Collections.Hashtable"
ParameterBinding(ConvertTo-StringByType): name="NewLineFormatProperty"; value="System.Collections.Hashtable"
ParameterBinding(ConvertTo-StringByType): name="Force"; value="True"
ParameterBinding(ConvertTo-StringByType): name="ArrayJoin"; value="True"
ParameterBinding(ConvertTo-StringByType): name="ArrayJoinString"; value=", "
ParameterBinding(ConvertTo-StringByType): name="AdvancedReplace"; value="System.Collections.Hashtable"
```

Over and over, only the sequence number is getting incremented. Is there a way to tell what is wrong?

Thank you

**Comment by PrzemyslawKlys** [comment]
You most likely have enabled powershell logging. This is what is causing it. This particular command is executed for every row of a table. Many rows, many unnessecary writes to event log. Disable this feature and problem will be solved. The workaround is to rewrite new-htmltable to not use recursive calls but that wont help much if your server is doing lots of similar calls.

**Comment by PrzemyslawKlys** [comment]
don't think that is related to new version. PSWriteHTML hasn't changed for months when it comes to that specific command.  Are you sure powershell logging has not been enabled between now and older run? Or maybe it was run somewhere else? I had exactly this issue at another Client where the reports were working fine for months, and suddently stopped and it was because they linked new GPO with powershell logging.

**Comment by SnakeSK** [comment]
Powershell logging is enabled for at least 2 years, its not logging into file, only to event log. Even now when I run the old version, it works without problems. Unfortunately there is no way we can disable PSLogging because of security :(

**Comment by PrzemyslawKlys** [comment]
Hrms, you're saying old version of GPOZaurr runs, and the new version doesn't run? on the very same server? with same PSWriteHTML?

**Comment by SnakeSK** [comment]
Yes, 0.0.158 runs ok

**Comment by SnakeSK** [comment]
Mine holds around 3 minutes (100MB)

**Comment by PrzemyslawKlys** [comment]
And so how useful it is for security purposes ? :-D
