### ISSUE TITLE
Report file not displaying "File Explorer" data properly

### ISSUE THREAD

**Issue by idhcbprojects2218363** [EvotecIT/GPOZaurr#51]
Hi All

First time I am posting an issue in githib for any project, Hopefully I am doing this correctly

Issue 
![image](https://github.com/EvotecIT/GPOZaurr/assets/47386349/9e0de129-1dd9-4cbf-a655-2d3c69a8079c)

I have run the following

`PS C:\Windows\system32> Invoke-GPOZaurr -verbose
[i][GPOZaurr] Version [Informative] Current/Latest: 1.0.0 at 09/17/2023 09:11:39
[i][GPOZaurr] Domain Information [Informative] Forest: Not defined. Using current one
[i][GPOZaurr] Domain Information [Informative] Included Domains: Not defined. Using all domains of forest
[i][GPOZaurr] Domain Information [Informative] Excluded Domains: No exclusions provided`

and then the report opens

file:///C:/Users/<USERNAME>.<DOMAINNAME>/AppData/Local/Temp/hi0cz3ju.html#WizardStep-jy3gd9i2

Going to 

1. Group Policy Content
2. FileExplorer
3. displays the following 

- DisplayName	DomainName	GUID	GpoType	DoNotRequestAlternateCredentials	RequestCredentialsForNetworkInstallations	TurnOffPreviewPane	SetADefaultAssociationsConfigurationFile	SetADefaultAssociationsConfigurat

Or this RAW code  `<html><body><!--StartFragment-->DisplayName | DomainName | GUID | GpoType | DoNotRequestAlternateCredentials | RequestCredentialsForNetworkInstallations | TurnOffPreviewPane | SetADefaultAssociationsConfigurationFile | SetADefaultAssociationsConfigurat-- | -- | -- | -- | -- | -- | -- | -- | --<!--EndFragment--></body></html>`

Is this a bug?

Regards
Iain

**Comment by PrzemyslawKlys** [comment]
DOes other tabs display something or no?

**Comment by idhcbprojects2218363** [comment]
> DOes other tabs display something or no?

Yes, all the other Tabs Display properly, listing the correct GPOs on the domain that contain settings which are covered by that Tab Category

**Comment by PrzemyslawKlys** [comment]
When you press F12 what does it say, it should show you errors. Something must be causing the html/js to break

**Comment by idhcbprojects2218363** [comment]
> When you press F12 what does it say, it should show you errors. Something must be causing the html/js to break

I am not sure if it is relevant errors, but I have two show up in the F12 development console
![image](https://github.com/EvotecIT/GPOZaurr/assets/47386349/bf56fca3-f39c-40e1-9e79-b3879eef87cf)

Code analysis using UltraEdit and HTML highlighting

Error 1
![image](https://github.com/EvotecIT/GPOZaurr/assets/47386349/464ebfa0-483a-45ff-b296-3962f955afab)

Error 2
![image](https://github.com/EvotecIT/GPOZaurr/assets/47386349/a6a06759-3e83-4892-9336-b13d4cc69bda)

**Comment by PrzemyslawKlys** [comment]
ye, pretty sure that's why it doesn't build. writting down to JS has an error. Its PSWriteHTML fault, but i would need to be able to replicate the issue on my own to be able to fix it.

**Comment by idhcbprojects2218363** [comment]
> ye, pretty sure that's why it doesn't build. writing down to JS has an error. Its PSWriteHTML fault, but i would need to be able to replicate the issue on my own to be able to fix it.

I think there is a valid "Timeout" issue. 

![image](https://github.com/EvotecIT/GPOZaurr/assets/47386349/c54a3c2a-7a65-47ff-9aa0-1e629a3b0181)

Is it possible to extend this ? 

If the data is in the report, and I expect it is, I could make an edit to get it to display correctly, but I would need to know what to change.

I am not against supplying the report file which has been generated. But I would have to make some redactions before sharing 

Regards
Iain

**Comment by idhcbprojects2218363** [comment]
I have noticed what needs to be added, just unsure of the cause. 

![image](https://github.com/EvotecIT/GPOZaurr/assets/47386349/bf1034d4-d5a6-479b-b9a3-864ef23c4f00)

I have this for File Explorer Display
`<div class="flexElement overflowHidden"><table width="100%" id="DT-mFFMlMIT" class="dataTables display compact"><thead><tr><th>DisplayName</th><th>DomainName</th><th>GUID</th><th>GpoType</th><th>DoNotRequestAlternateCredentials</th> ....  [ not the full content from the element node]`

For the next display over it starts 
`<div class="flexElement overflowHidden"><div id="DT-kMqWVFhe_wrapper" class="dataTables_wrapper"><div class="dt-buttons">               <button class="dt-button buttons-copy buttons-html5" tabindex="0" aria-controls="DT-kMqWVFhe" type="button"><span>Copy</span></button> <button class="dt-button buttons-excel buttons-html5" tabindex="0" aria-controls="DT-kMqWVFhe" type="button"><span>Excel</span></button> <button class="dt-button buttons-csv buttons-html5" tabindex="0" aria-controls="DT-kMqWVFhe" type="button"><span>CSV</span></button> <button class="dt-button buttons-pdf buttons-html5" tabindex="0" aria-controls="DT-kMqWVFhe" type="button"><span>PDF</span></button> <button class="dt-button buttons-collection buttons-page-length" tabindex="0" aria-controls="DT-kMqWVFhe" type="button" aria-haspopup="dialog"><span>Show 15 rows</span>  ...  [ not the full content from the element node] `

**Comment by PrzemyslawKlys** [comment]
Timeout doesn't matter, it's a problem with GPO, or rather problem with property having quotes inside which is not escaped properly by PSWriteHTML module. You would need to find those GPOs it tries to display and then kind of find which property it's failing exactly then try to build [Pscustomobject] with exactly same data that replicates the problem when you do $Object | Out-HtmlView -DataStore Javascript

**Comment by idhcbprojects2218363** [comment]
I have fixed it 

the Line `"data":"Remove\"MapNetworkDrive\"And\"DisconnectNetworkDrive\""},{`   which is Error 2 listed in my post above does not have the correct escaped characters

[](https://github.com/EvotecIT/GPOZaurr/issues/51#issuecomment-1822547893)

originally this `"data":"Remove\MapNetworkDrive"And"DisconnectNetworkDrive""},{`   so the content of  `Invoke-GPOZaurrContent.ps1`   is not escaping the field `Remove"MapNetworkDrive"And"DisconnectNetworkDrive"`  which is a valid GPO policy Key.

**Comment by idhcbprojects2218363** [comment]
> This can be replicated with
> 
> ```postscript
> $Test = [PSCustomObject] @{
>     'This is "A test", " for more tests"' = "Hello"
>     "ABC"                                 = "123"
> }
> 
> $Test | Out-HtmlView -DataStore JavaScript -Filtering
> $Test | Out-HtmlView -Filtering
> ```
> 
> The first HTML fails. This requires a fix on PSWriteHTML, and is not directly a problem of GPOZaurr

I generally agree with you, and the image below is the actual GPO key in GPMC which is listed under that display category which "PSWriteHTML" is having an issue with.
![image](https://github.com/EvotecIT/GPOZaurr/assets/47386349/6447304c-ede3-4530-b133-5233b44fc14f)

The odd thing, though, when you look at the report " HTML file ", is that there is a line close by above with the correct syntax to work, but it needs the rest of the wrapping to be processed.

![image](https://github.com/EvotecIT/GPOZaurr/assets/47386349/593e85f4-ce3f-4d31-8950-77d71ab526d8)

the opening  `"data":"` at the start of the line  and the closing `},{`  

Regards
Iain

**Comment by PrzemyslawKlys** [comment]
You can do:

```ps
Install-Module PSWriteHTML -Force -Verbose -AllowPrerelease
```

I've released new version that does this differently. Let me know what is the result on whole GPOZaurr. Remember to restart powershell after installing the prerelease version
