### ISSUE TITLE
Issue on the latest release GPOZaurr - Current: 1.1.0 (Get-ADObject : Directory object not found)

### ISSUE THREAD

**Issue by SokratisUNI** [EvotecIT/GPOZaurr#52]
Hello,

First of all I would like to say thank you for all your hard work.
It seems that there's an issue with the latest release when trying to run the below:
`Invoke-GPOZaurr -Domain myLab.local -FilePath .\report.html`

![image](https://github.com/EvotecIT/GPOZaurr/assets/72577742/a458249b-a0bc-41f4-a658-8a3c07da4fe8)

And the full error is:
=================
PS C:\> $Error[-2] | Format-List * -Force

PSMessageDetails      :
Exception             : Microsoft.ActiveDirectory.Management.ADIdentityNotFoundException: Directory object not found
                        ---> System.ServiceModel.FaultException: The failed operation was attempted on a non-existent
                        directory object.
                           --- End of inner exception stack trace ---
                           at
                        Microsoft.ActiveDirectory.Management.AdwsConnection.ThrowExceptionForExtendedError(String
                        extendedErrorMessage, Exception innerException)
                           at Microsoft.ActiveDirectory.Management.AdwsConnection.ThrowExceptionForErrorCode(String
                        message, String errorCode, String extendedErrorMessage, Exception innerException)
                           at
                        Microsoft.ActiveDirectory.Management.AdwsConnection.ThrowExceptionForFaultDetail(FaultDetail
                        faultDetail, FaultException faultException)
                           at Microsoft.ActiveDirectory.Management.AdwsConnection.ThrowException(AdwsFault adwsFault,
                        FaultException faultException)
                           at Microsoft.ActiveDirectory.Management.AdwsConnection.Search(ADSearchRequest request)
                           at Microsoft.ActiveDirectory.Management.ADWebServiceStoreAccess.Microsoft.ActiveDirectory.Ma
                        nagement.IADSyncOperations.Search(ADSessionHandle handle, ADSearchRequest request)
                           at Microsoft.ActiveDirectory.Management.ADObjectSearcher.PagedSearch(Object& pageCookie,
                        Boolean& hasSizeLimitExceeded, Int32 pageSize, Int32 sizeLimit)
                           at Microsoft.ActiveDirectory.Management.ADObjectSearchResultEnumerator.System.Collections.IE
                        numerator.MoveNext()
                           at Microsoft.ActiveDirectory.Management.Commands.ADFactory`1.<GetExtendedObjectFromFilter>d_
                        _33.MoveNext()
                           at Microsoft.ActiveDirectory.Management.Commands.ADGetCmdletBase`3.OutputSearchResults(IADOP
                        athNode filter)
                           at
                        Microsoft.ActiveDirectory.Management.Commands.ADGetCmdletBase`3.ADGetCmdletBaseBeginCSRoutine()
                           at Microsoft.ActiveDirectory.Management.CmdletSubroutinePipeline.Invoke()
                           at Microsoft.ActiveDirectory.Management.Commands.ADCmdletBase`1.BeginProcessing()
TargetObject          :
CategoryInfo          : ObjectNotFound: (:) [Get-ADObject], ADIdentityNotFoundException
FullyQualifiedErrorId : ActiveDirectoryCmdlet:Microsoft.ActiveDirectory.Management.ADIdentityNotFoundException,Microsof
                        t.ActiveDirectory.Management.Commands.GetADObject
ErrorDetails          :
InvocationInfo        : System.Management.Automation.InvocationInfo
ScriptStackTrace      : at Get-WinADDuplicateObject, C:\Program
                        Files\WindowsPowerShell\Modules\GPOZaurr\1.1.0\GPOZaurr.psm1: line 2584
                        at Get-GPOZaurrDuplicateObject, C:\Program
                        Files\WindowsPowerShell\Modules\GPOZaurr\1.1.0\GPOZaurr.psm1: line 21390
                        at <ScriptBlock>, C:\Program Files\WindowsPowerShell\Modules\GPOZaurr\1.1.0\GPOZaurr.psm1:
                        line 14612
                        at Invoke-GPOZaurr, C:\Program Files\WindowsPowerShell\Modules\GPOZaurr\1.1.0\GPOZaurr.psm1:
                        line 24436
                        at <ScriptBlock>, <No file>: line 1
PipelineIterationInfo : {}

**Comment by PrzemyslawKlys** [comment]
Does it work with earlier version?

**Comment by SokratisUNI** [comment]
I've tried the latest module towards a few systems (Server 2022) and had the same exact error.

Yes, it worked just fine, actually I was working on it yesterday.

Let me know if you need any additional info / logs.

**Comment by SokratisUNI** [comment]
Not sure what's wrong, maybe I'm doing something wrong...

Just force-installed from again and "invoke-gpozaurr" is not there anymore.

I hope am not doing something wrong here....
++++++++++++++++++++++++++++++++
PS C:\> install-module -name gPOZaurr -Scope AllUsers -Force

PS C:\> Import-Module GPOZaurr -Verbose
VERBOSE: Loading module from path 'C:\Program Files\WindowsPowerShell\Modules\GPOZaurr\1.1.0\GPOZaurr.psd1'.
VERBOSE: Populating RepositorySourceLocation property for module GPOZaurr.                                              VERBOSE: Loading module from path 'C:\Program Files\WindowsPowerShell\Modules\GPOZaurr\1.1.0\GPOZaurr.psm1'.            VERBOSE: Importing function 'Export-GPOZaurrContent'.
VERBOSE: Importing function 'Get-GPOZaurrBrokenLink'.
VERBOSE: Importing function 'Get-GPOZaurrMissingFiles'.
VERBOSE: Importing function 'Get-GPOZaurrOrganizationalUnit'.
VERBOSE: Importing function 'Get-GPOZaurrPermissionAnalysis'.
VERBOSE: Importing function 'Get-GPOZaurrPermissionIssue'.
VERBOSE: Importing function 'Get-GPOZaurrRedirect'.
VERBOSE: Importing function 'Get-GPOZaurrUpdates'.
VERBOSE: Importing function 'Invoke-GPOZaurrContent'.
VERBOSE: Importing function 'Remove-GPOZaurrLinkEmptyOU'.
VERBOSE: Importing function 'Repair-GPOZaurrBrokenLink'.
VERBOSE: Importing function 'Repair-GPOZaurrPermission'.
VERBOSE: Importing function 'Set-GPOZaurrStatus'.
VERBOSE: Importing function 'Skip-GroupPolicy'.
VERBOSE: Importing alias 'Find-GPO'.
PS C:\>

**Comment by PrzemyslawKlys** [comment]
Make sure import-module activedirectory and grouppolicy are working

**Comment by SokratisUNI** [comment]
Will do some more testing and let you know.
Yep, already did that. 
Tried to run it on server member and on an DC, for some reason it doesn't wants to cooperate today :)

Thanks for your help.

**Comment by SokratisUNI** [comment]
Baahh, doing to many things at the same time doesn't help 👎 
The import module works just fine, I've tried on a server where GP was not installed thus the result above.

Still getting the same error "At C:\Program Files\WindowsPowerShell\Modules\GPOZaurr\1.1.0\GPOZaurr.psm1:2584 char:24".

Thanks again for your efforts.

**Comment by PrzemyslawKlys** [comment]
Can you run `Get-WinADDuplicateObject -Verbose` and let me know when it crashes. If it doesn't crash run `Get-GPOZaurrDuplicateObject -Verbose` to confirm

**Comment by SokratisUNI** [comment]
Hi, here's the result.
Had the same result using PS 5.1 and PWSH 7.4.1
After the errors pasted below, it seems that is working fine, is able to find some duplicates GP.

-------------------------------------------------------------------
PS C:\Users\Admin\Desktop> Get-WinADDuplicateObject -Verbose
Get-WinADDuplicateObject : The term 'Get-WinADDuplicateObject' is not recognized as the name of a cmdlet, function,
script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is
correct and try again.
At line:1 char:1
+ Get-WinADDuplicateObject -Verbose
+ ~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Get-WinADDuplicateObject:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

PS C:\Users\Admin\Desktop> Get-GPOZaurrDuplicateObject -Verbose
VERBOSE: Get-WinADDuplicateObject - Processing MyLab.local
VERBOSE: Get-WinADDuplicateObject - Processing MyLab.local - DC=MyLab,DC=local
VERBOSE: Get-WinADDuplicateObject - Processing MyLab.local - DC=DomainDnsZones,DC=MyLab,DC=local
Get-ADObject : Directory object not found
At C:\Program Files\WindowsPowerShell\Modules\GPOZaurr\1.1.0\GPOZaurr.psm1:2584 char:24
+ ...      $Objects = Get-ADObject @getADObjectSplat -SearchBase $Partition
+                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (:) [Get-ADObject], ADIdentityNotFoundException
    + FullyQualifiedErrorId : ActiveDirectoryCmdlet:Microsoft.ActiveDirectory.Management.ADIdentityNotFoundException,M
   icrosoft.ActiveDirectory.Management.Commands.GetADObject

VERBOSE: Get-WinADDuplicateObject - Processing root.local
VERBOSE: Get-WinADDuplicateObject - Processing root.local - CN=Configuration,DC=root,DC=local
VERBOSE: Get-WinADDuplicateObject - Processing root.local - DC=ForestDnsZones,DC=root,DC=local
Get-ADObject : A referral was returned from the server
At C:\Program Files\WindowsPowerShell\Modules\GPOZaurr\1.1.0\GPOZaurr.psm1:2584 char:24
+ ...      $Objects = Get-ADObject @getADObjectSplat -SearchBase $Partition
+                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ResourceUnavailable: (:) [Get-ADObject], ADReferralException
    + FullyQualifiedErrorId : ActiveDirectoryServer:8235,Microsoft.ActiveDirectory.Management.Commands.GetADObject

VERBOSE: Get-WinADDuplicateObject - Processing root.local - DC=root,DC=local
VERBOSE: Get-WinADDuplicateObject - Processing root.local - DC=DomainDnsZones,DC=root,DC=local
Get-ADObject : Directory object not found
At C:\Program Files\WindowsPowerShell\Modules\GPOZaurr\1.1.0\GPOZaurr.psm1:2584 char:24
+ ...      $Objects = Get-ADObject @getADObjectSplat -SearchBase $Partition
+                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (:) [Get-ADObject], ADIdentityNotFoundException
    + FullyQualifiedErrorId : ActiveDirectoryCmdlet:Microsoft.ActiveDirectory.Management.ADIdentityNotFoundException,M
   icrosoft.ActiveDirectory.Management.Commands.GetADObject

**Comment by PrzemyslawKlys** [comment]
Ok, i think I know what could be wrong. You don't have domaindnszones, but only forest zones. I'll try to do some verification first, and fix it.

**Comment by PrzemyslawKlys** [comment]
What about ` get-adrootdse` can you list me things in namingcontexts?

**Comment by SokratisUNI** [comment]
Yeah, here it is:

`PS C:\Users\Admin> Get-ADRootDSE

configurationNamingContext    : CN=Configuration,DC=root,DC=local
currentTime                   : 2/7/2024 11:19:01 AM
defaultNamingContext          : DC=MyLab,DC=local
dnsHostName                   : DC01.MyLab.local
domainControllerFunctionality : Windows2016
domainFunctionality           : Windows2016Domain
dsServiceName                 : CN=NTDS Settings,CN=DC01,CN=Servers,CN=Default-First-Site-Name,CN=Sites,CN=Configuration,DC=root,DC=local
forestFunctionality           : Windows2016Forest
highestCommittedUSN           : 172409633
isGlobalCatalogReady          : {TRUE}
isSynchronized                : {TRUE}
ldapServiceName               : root.local:dc01$@MyLab.local
namingContexts                : {CN=Configuration,DC=root,DC=local,CN=Schema,CN=Configuration,DC=root,DC=local,DC=MyLab,DC=local}
rootDomainNamingContext       : DC=root,DC=local
schemaNamingContext           : CN=Schema,CN=Configuration,DC=root,DC=local
serverName                    : CN=DC01,CN=Servers,CN=Default-First-Site-Name,CN=Sites,CN=Configuration,DC=root,DC=local
subschemaSubentry             : CN=Aggregate,CN=Schema,CN=Configuration,DC=root,DC=local


PS C:\Users\Admin>`

**Comment by PrzemyslawKlys** [comment]
Ok, so it seems you have neither ForestDnsZones or DomainDnsZones in your forest - how is that possible? Do you have some special DNS settings in your forest?

**Comment by PrzemyslawKlys** [comment]
Ye, i will do additional checks and ignore this + give warnings. You will just ignore warnings. I don't like RED :)

**Comment by SokratisUNI** [comment]
haha me too :).
Thanks for your time.

**Comment by PrzemyslawKlys** [comment]
SHould be fixed. Install new version and retry.

**Comment by SokratisUNI** [comment]
Thanks @PrzemyslawKlys , new version works perfectly and I do get the DNS zone not found warning.
