### ISSUE TITLE
Remove-GPOZaurrLinkEmptyOU - Unlink unused Group 

### ISSUE THREAD

**Issue by kelsey-work** [EvotecIT/GPOZaurr#53]
In the Steps to fix this, the suggested resolution states to run once with -Whatif then in the second part where it states if you are happy to run the code, it shows -Whatif again
![GpozaurrWhatif-issue](https://github.com/EvotecIT/GPOZaurr/assets/83051607/8dbdd13f-ed77-487b-a113-f8cd558ae516)

**Comment by PrzemyslawKlys** [comment]
Thanks
