### ISSUE TITLE
Get GPO by type (LAPS)

### ISSUE THREAD

**Issue by Syrusback** [EvotecIT/GPOZaurr#57]
Hello,

I've read the documentation and tried several methods but I'm still unsure how to retrieve an object in PowerShell with a list of GPOs that have LAPS configured. 

![image](https://github.com/EvotecIT/GPOZaurr/assets/175196018/0cadf36c-ef0b-4592-b648-d6642d91b4be)

Could you please provide guidance on how to achieve this?

Thank you

**Comment by PrzemyslawKlys** [comment]
Is it not showing you a table with LAPS GPOs?

**Comment by PrzemyslawKlys** [comment]
`Invoke-GPOZaurrContent -Type LAPS`

![image](https://github.com/EvotecIT/GPOZaurr/assets/15063294/ac3e8e3a-cdd0-4cea-8f77-255a4d60e69e)

**Comment by Syrusback** [comment]
ok thanks a lot :)
