### ISSUE TITLE
SplitReports functionality causes Exception

### ISSUE THREAD

**Issue by cflanderscpc** [EvotecIT/GPOZaurr#58]
When running `Invoke-GPOZaurr -SplitReports` The step immediately before "Generating HTML Report" triggers the following exception:

```
Exception calling "GetDirectoryName" with "1" argument(s): "The path is not of a legal form."
At C:\Program Files\WindowsPowerShell\Modules\GPOZaurr\1.1.5\GPOZaurr.psm1:20832 char:5
+     $DirectoryName = [io.path]::GetDirectoryName($FilePath)
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : ArgumentException
```

This error does not occur if not using the `-SplitReports` functionality.

**Comment by PrzemyslawKlys** [comment]
Ye, it's because I assume giving it FilePath, when in this case you run it without.

**Comment by cflanderscpc** [comment]
Interesting.   I assumed that omitting filepath would use `$PSScriptRoot` or `$PWD`

**Comment by PrzemyslawKlys** [comment]
We use temp folder by default. SplitReports was added only a bit later, but I assumed it would be for people wanting to be more direct on where to save the report
