### ISSUE TITLE
Error IsAclConsistent is missing

### ISSUE THREAD

**Issue by Hs-WallKey** [EvotecIT/GPOZaurr#59]
When I run this command `Invoke-GPOZaurr -FilePath .\GPOZaurrPermissionsInconsistent.html -Verbose -Type GPOConsistency`, I get this warning on all my GPOs :
```
VERBOSE: Get-GPOZaurrPermissionConsistency - Processing [XXXXXX](1/48) GPO - Loopback Processing mode Fusionner
WARNING: Get-GPOZaurrPermissionConsistency - Processing GPO - Loopback Processing mode Fusionner / XXXXXX failed to get consistency with error: Method invocation failed because [Deserialized.Microsoft.GroupPolicy.Gpo] does not contain a method named 'IsAclConsistent'..
```

I've checked the GPO rights on AD and SYSVOL and they seem consistent, so I don't know where else to look. Do you have any idea what the problem is?

![image](https://github.com/user-attachments/assets/86fa2a10-0226-4996-9cd5-06449ace8afa)

**Comment by PrzemyslawKlys** [comment]
Use PowerShell 5.1, PS 7 doesn't support GroupPolicy module in full mode, and is running in compatibility mode which means methods are not available.

**Comment by Hs-WallKey** [comment]
Perfect, it works! Thanks a lot!
