### ISSUE TITLE
Group Policy Content - Windows Time Service

### ISSUE THREAD

**Issue by wahayoyo** [EvotecIT/GPOZaurr#6]
Requesting a section be added for the finding GPOs that are adjusting Windows Time/NTP Settings.

These settings are located at: Computer Configuration/Administrative Templates/System/Windows Time Service

Specifically the most important settings are "Configure Windows NTP Client" and the option NTPServer within that.

**Comment by PrzemyslawKlys** [comment]
Added. 

![image](https://user-images.githubusercontent.com/15063294/105761937-06beef00-5f54-11eb-82a5-e36476ecf554.png)
