### ISSUE TITLE
Advanced Audit Policy Configuration settings

### ISSUE THREAD

**Issue by wd-swaters** [EvotecIT/GPOZaurr#62]
Hello -

Big fan of the project.  I just stumbled across it a week or two ago.

As far as I can see, Advanced Audit Policy Configuration settings are not represented in the Group Policy Content report.

My apologies if I am wrong, but I've looked everywhere.

Is the omission 'by design', overlooked, or is there some other reason?

Thank you.

**Comment by PrzemyslawKlys** [comment]
Isn't it part of Audit?

```powershell
Invoke-GPOZaurr -Type GPOAnalysis
```

![image](https://github.com/user-attachments/assets/d5b353ad-ed25-4716-a530-86d397af0d2a)

**Comment by PrzemyslawKlys** [comment]
Look at the screenshot. It matches what you need. Just because tab is called Audit doesnt mean it doesnt refer to something else?

**Comment by wd-swaters** [comment]
I didn't see the settings I am looking for as columns.  I did however see the settings I am looking for when I expanded the GPO's line in the report.

![image](https://github.com/user-attachments/assets/b1be8723-c29f-4a20-8c17-4dc4cf45588d)

Thank you for the quick responses.
