### ISSUE TITLE
Write-Error: Failed to run Invoke-GPOZaurr. Error: Unable to find type [Microsoft.GroupPolicy.Gpo].

### ISSUE THREAD

**Issue by thetechgy** [EvotecIT/GPOZaurr#65]
I've previously used GPOZaurr and am now trying to use it in a new environment. I'm running this command:

`Invoke-GPOZaurr -FilePath $filePath -PassThru -HideHTML -Verbose`

And I get this error (modified slightly for security/privacy):
`WARNING: Get-PrivGPOZaurrLink - Couldn't find link domain.com[GUID] in a GPO Cache. Lack of permissions for given GPO? Are you running as admin? Skipping.
VERBOSE: Get-GPOZaurr - Processing [domain.com](1/452) 
Write-Error: Failed to run Invoke-GPOZaurr. Error: Unable to find type [Microsoft.GroupPolicy.Gpo].`

Any suggestions on how I can resolve this? I don't currently have Domain Admin and I'm running this from a server with RSAT installed but not a domain controller - are either of those prerequisites?

**Comment by PrzemyslawKlys** [comment]
Use PowerShell 5.1, PS 7 doesn't work correctly.

**Comment by thetechgy** [comment]
Thank you - that resolved the issue. I didn't realize it was trying to use 7
