### ISSUE TITLE
[Group Policy Organizational Units] Cannot index into a null array

### ISSUE THREAD

**Issue by musklor** [EvotecIT/GPOZaurr#67]
Hi,
when I launch your fabulous script, I have a lot of lines with "cannot index into a null array".

Level : Group Policy Organizational Units

Cannot index into a null array.
At .....GPOZaurr.psm1:26406 char:25
$CachedOu[$OU] ['Objects'] [$Object.DistinguishedName] = $O ....

**Comment by PrzemyslawKlys** [comment]
You need to provide a lot more information on what you're doing

**Comment by musklor** [comment]
I have just launched "Invoke-GPOZaurr -FilePath "...."

**Comment by PrzemyslawKlys** [comment]
You're not giving me much to go on. I can't reproduce this from you having an issue.

It fails on following code:

```powershell
            $ObjectsInOu = Get-ADObject -LDAPFilter "(|(ObjectClass=user)(ObjectClass=contact)(ObjectClass=computer)(ObjectClass=group)(objectClass=inetOrgPerson)(ObjectClass=PrintQueue))" -SearchBase $TopOU.distinguishedName -Server $ForestInformation['QueryServers'][$Domain]['hostname'][0]
            Write-Verbose "Get-GPOZaurrOrganizationalUnit - Processing $($Domain) / $($TOPOU.DistinguishedName) [$CountTop/$($TopOrganizationalUnits.Count)], found $($ObjectsInOu.Count) objects to process."
            foreach ($Object in $ObjectsInOu) {
                $Place = ConvertFrom-DistinguishedName -ToOrganizationalUnit -DistinguishedName $Object.DistinguishedName
                $AllOUs = ConvertFrom-DistinguishedName -ToMultipleOrganizationalUnit -IncludeParent -DistinguishedName $Place
                foreach ($OU in $AllOUs) {
                    if ($OU -eq $Place) {
                        $CachedOu[$OU]['Objects'][$Object.DistinguishedName] = $Object
                        $CachedOu[$OU]['ObjectsClasses'][$Object.ObjectClass] = ''
                        $CachedOu[$OU]['ObjectsCountDirect']++
                    }
                    else {
                        $CachedOu[$OU]['ObjectsClasses'][$Object.ObjectClass] = ''
                        $CachedOu[$OU]['ObjectsCountIndirect']++
                    }
                    $CachedOu[$OU]['ObjectsCountTotal']++
                }
            }
```

Using -Verbose should provide some information, but I guess if it fails it has to give you more information than just cannot index into null array

**Comment by PrzemyslawKlys** [comment]
Is there anything special about that OU?

**Comment by musklor** [comment]
I have to investigate

**Comment by musklor** [comment]
I think it's related to the Organizational Units security. My service account has not access to some OU.

**Comment by PrzemyslawKlys** [comment]
Does it display that verbose message with domain and count and all that properly and then crashes?

**Comment by musklor** [comment]
Yes, absolutely !
I have some errors but I have no crashes.

05/10 ... count
Errors
06/10 .... count

**Comment by PrzemyslawKlys** [comment]
You really need to provide something more. The verbose line is much longer.

**Comment by musklor** [comment]
Sorry, I'll send you a complete log tomorrow.

**Comment by musklor** [comment]
[gpozaurr.log](https://github.com/user-attachments/files/17811821/gpozaurr.log)

**Comment by PrzemyslawKlys** [comment]
Can you run:

`$ObjectsInOu = Get-ADObject -LDAPFilter "(|(ObjectClass=user)(ObjectClass=contact)(ObjectClass=computer)(ObjectClass=group)(objectClass=inetOrgPerson)(ObjectClass=PrintQueue))" -SearchBase "YOUR OU THAT FAILS" -Server  YOURDC` and see what objects you see there and whether they are missing DN or ObjectClass => because if you can read objects in that OU, and at the same time you can't get DN/ObjectClass this is where it gets the errors. I will apply logic to remove errors but this would make sense

**Comment by musklor** [comment]
I have an OU with nothing inside.

**Comment by PrzemyslawKlys** [comment]
> VERBOSE: Get-GPOZaurrOrganizationalUnit - Processing domain.ad.com / OU=xx,DC=xx,DC=xx,DC=xx [5/10], found 743 objects to process.
> Cannot index into a null array.
> At C:\Windows\system32\WindowsPowerShell\v1.0\Modules\GPOZaurr\GPOZaurr.psm1:26406 char:25
> + ...             $CachedOu[$OU]['Objects'][$Object.DistinguishedName] = $O ...
> +                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>     + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
>     + FullyQualifiedErrorId : NullArray
> Cannot index into a null array.

Your log file says you have 743 objects inside and it fails. It fails on DN/ObjectClass so something is returned...

**Comment by musklor** [comment]
I have some symbols in some names "GL-..-Z@...". Maybe an issue ?

**Comment by PrzemyslawKlys** [comment]
this is one specific OU, look at your log, find the one with found 743, and then query for it and see if it has DN in it. remember to use your service account tho

**Comment by PrzemyslawKlys** [comment]
> I have some symbols in some names "GL-..-Z@...". Maybe an issue ?

could be can you provide me a list of those that look special when it comes to their "DN" name? like full DN with replaced parts

**Comment by musklor** [comment]
I have OU name with space :
- CN=GLD_S-xx_OU-xxx-Ress-Serv-xxx_Comp_xxx,OU=xxx xxx xxx,OU=Gestion AD,DC=xx,DC=xx,DC=xx

**Comment by PrzemyslawKlys** [comment]
that's fine, anything else?

**Comment by musklor** [comment]
Two lines with a dot "."

CN=GG-xx-xx.xx,OU=xx,OU=XX xx,OU=XXXX XXX,DC=xx,DC=xxx,DC=xxx

**Comment by PrzemyslawKlys** [comment]
You mentioned one with @?

**Comment by musklor** [comment]
Yes, in one OU I have :
- CN=GG-XX-XXX.X,OU=XXX,OU=XX XX,OU=XX XX,DC=XX,DC=XX,DC=XX
- CN=GL-XX-Z@XX,OU=XX,OU=XX,OU=XXX,DC=XX,DC=XX,DC=XXX

**Comment by PrzemyslawKlys** [comment]
I added some fail safe and additional reporting to figure this out. Try running new version and let me know if warnings appear and what they show

**Comment by musklor** [comment]
Hi thanks a lot. We found the issues.
- some groups are duplicate with CNF in their name (when you create groups in two DCs at the same time.)
- some rights problem
We plan to fix this issues and relaunch the script in january.
