### ISSUE TITLE
 Questions About Policy Optimization

### ISSUE THREAD

**Issue by Emeric-IT** [EvotecIT/GPOZaurr#69]
Hello,

I have two questions regarding this report:

- The Default Domain Policy and Default Domain Controllers Policy are not optimized. What do you think about disabling the computer settings in these policies?

- I have a Group Policy Preference (GPP) with a problematic status. The configuration part of the GPP targets computers and I’ve disabled the user configuration. However, this report indicates that the optimization is still not satisfactory. (see attached picture: GPP Problem.png)
![GPP Problem](https://github.com/user-attachments/assets/76229951-508c-4e01-9e6c-17a0b90eee37)

Could you please share your thoughts or suggestions on these points?

Best regards,

**Comment by PrzemyslawKlys** [comment]
I'll take a look at underlying logic, maybe there is a mistake there.

**Comment by PrzemyslawKlys** [comment]
Ok, I see where the prbolem comes from:

![image](https://github.com/user-attachments/assets/4b8c7d6d-65d2-454f-83fd-c1706249973c)

The code detected UserPolicies inside (in XML) , while the user policy is disabled. Now why that GUI of yours doesn't show the data is real question ;)

**Comment by Emeric-IT** [comment]
For this case : 
![image](https://github.com/user-attachments/assets/dad66982-ce03-4fc3-ae6b-19899b7e2100)
I don't know if it is good practice to disable user configuration (for users who have no settings) on this default GPO.
