### ISSUE TITLE
Invoke-GPOZaurr : Le terme « Invoke-GPOZaurr » n'est pas reconnu comme nom d'applet de commande

### ISSUE THREAD

**Issue by tocks53** [EvotecIT/GPOZaurr#8]
Hello,

Thanks for your job.

I have install your module

But the module not running 

PS C:\Users\administrateur> Import-Module GPOZaurr
PS C:\Users\administrateur> Get-Module

ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Binary     1.0.0.0    CimCmdlets                          {Export-BinaryMiLog, Get-CimAssociatedInstance, Get-CimClass, Get-CimInstance...}
Script     0.0.114    GPOZaurr                            {Get-GPOZaurrBrokenLink, Get-GPOZaurrPermissionAnalysis, Get-GPOZaurrPermissionIssue, Invoke-GPOZaurrContent...}
Manifest   3.1.0.0    Microsoft.PowerShell.Management     {Add-Computer, Add-Content, Checkpoint-Computer, Clear-Content...}
Manifest   3.0.0.0    Microsoft.PowerShell.Security       {ConvertFrom-SecureString, ConvertTo-SecureString, Get-Acl, Get-AuthenticodeSignature...}
Manifest   3.1.0.0    Microsoft.PowerShell.Utility        {Add-Member, Add-Type, Clear-Variable, Compare-Object...}
Script     2.0.0      PSReadline                          {Get-PSReadLineKeyHandler, Get-PSReadLineOption, Remove-PSReadLineKeyHandler, Set-PSReadLineKeyHandler...}
Script     0.0.131    PSWriteHTML                         {Add-HTML, Add-HTMLScript, Add-HTMLStyle, ConvertTo-CascadingStyleSheets...}

PS C:\Users\administrateur> Invoke-GPOZaurr
Invoke-GPOZaurr : Le terme « Invoke-GPOZaurr » n'est pas reconnu comme nom d'applet de commande, fonction, fichier de script ou programme exécutable. Vérifiez l'orthographe du nom, ou si un chemin d'accès existe, vérifiez que le chemin d'accès est correct et réessayez.
Au caractère Ligne:1 : 1
+ Invoke-GPOZaurr
+ ~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Invoke-GPOZaurr:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

PS C:\Users\administrateur>

Help please

**Comment by PrzemyslawKlys** [comment]
You need to install RSAT - GroupPolicy and Active Directory. 

```
Get-Module -ListAvailable GroupPolicy
Get-Module -ListAvailable ActiveDirectory
```

Must work.

**Comment by tocks53** [comment]
Thanks a lot, its ok ,now.

your module is over GOOD.
